### ISSUE TITLE
G402 should consider Go version

### ISSUE THREAD

**Issue by loganrosen** [securego/gosec#1054]
### Summary 
golang/go#45428 landed in Go 1.18, and it sets the default minimum TLS version for clients to 1.2. Because of this, gosec shouldn't flag TLS client config without an explicit minimum version as a problem, as long as the Go version is >= 1.18.

### Steps to reproduce the behavior
Create an HTTP transport with a TLS client config like the following:
```
t := &http.Transport{
	TLSClientConfig: &tls.Config{},
}
```

Run gosec against this code on Go >= 1.18.

### gosec version
v2.15.0

### Go version (output of 'go version')
go version go1.20.2 darwin/arm64

### Operating system / Environment
macOS 13.6

### Expected behavior
gosec doesn't flag the code, as the minimum TLS version for the client is already 1.2 by default.

### Actual behavior
gosec flags the code.

**Comment by ccojocar** [comment]
I think what is happening here is the MinVersion is set to `0` when you initialise the `TLSClientConfig` default value &tls.Config{} and the scanners detects this. 

It is true that the go tls client doesn't support TLS versions lower than 1.2 but that is at the protocol level https://cs.opensource.google/go/go/+/refs/tags/go1.21.3:src/crypto/tls/common.go;l=1037, the configuration still remains to the insecure default value. 

I think it might be dangerous to rely on default implementation instead of setting explicitly a secure default value. It might happen that the 1.2 version gets insecure but the default implementation doesn't not get updated. 

I think is still worth to flag out that the code sets an insecure value while relying on a secure implementation of the protocol which is not made explicit in the configuration.  For instance, the go could overwrite the default configuration to something more secure, and the scanner will detect this but it doesn't do that (see the implementation in crypto/tls/common.go).

**Comment by loganrosen** [comment]
Fair enough, thanks for the explanation!

**Comment by bcho** [comment]
@ccojocar is that possible to have a config flag to allow suppress this? We want this as we are fine to use the default TLS 1.2 in the `tls.Config` and we know we will bump go to use the latest version to mitigate any future obsolete issues.

**Comment by jerome-laforge** [comment]
For mTLS httpclient, I used:
```go
t := http.DefaultTransport.(*http.Transport).Clone()
t.TLSClientConfig = &tls.Config{
	Certificates: []tls.Certificate{cert},
}
```
but gosec alerts:
```
 G402: TLS MinVersion too low. (gosec)
                t.TLSClientConfig = &tls.Config{
                        Certificates: []tls.Certificate{cert},
             }
``` 

with `nolint` tag, no alert but we remove gosec check on `tls.Config`.
```go
t := http.DefaultTransport.(*http.Transport).Clone()
t.TLSClientConfig = &tls.Config{ //nolint: gosec
	Certificates: []tls.Certificate{cert},
}
```

the final workaround that I used is:
```go
t := http.DefaultTransport.(*http.Transport).Clone()
t.TLSClientConfig.Certificates = []tls.Certificate{cert}
```

**Comment by MarioVilas** [comment]
Please reconsider reopening this issue. Using the default (as explained above) is a good security practice, this rule should check for the go version instead, since the real problem would be using the default in an *old* version of go, as opposed to using the default at all.

**Comment by karelbilek** [comment]
Put G402 to ignore, move on with your life.

The default is secure.

edit: to make sure I agree with you, this should be reopened. It's noise. But 🤷 not the first linter thing I put to ignore
