### ISSUE TITLE
G601 with go version 1.22 or later

### ISSUE THREAD

**Issue by dowben** [securego/gosec#1099]
### Summary 
As of go 1.22, the underlying issue in the go language has been fixed such that re-declaring loop variables is no longer necessary to prevent memory aliasing related bugs. Requesting an updated to gosec that does not raise G601 for go code that requires go version 1.22 or greater 

### Steps to reproduce the behavior
```
for _, item := range items {
	cpItem = &item
	break
}
```

### gosec version
2.18.2

### Go version (output of 'go version')
go version go1.22.0 

### Operating system / Environment
linux/amd64

### Expected behavior
No issue raised

### Actual behavior
G601 is raised

**Comment by ccojocar** [comment]
We usually try to avoid handling the go version inside of a rule since there are at least two major go versions supported, and we want to not make any assumptions. 

We will normally phased out the rule when doesn't make sense for all supported Go version. This will hopefully happen in a future release.

I would recommend for now to just exclude it if you try to scan a project on Go 1.22.
