### ISSUE TITLE
GitHub action `v2.21.2` uses ` securego/gosec:2.21.1`docker image with broken SARIF output

### ISSUE THREAD

**Issue by nickeskov** [securego/gosec#1219]
### Summary 
Problem described in #1214 still appears. GitHub action `v2.21.2` still uses `securego/gosec:2.21.1` docker image. The error with SARIF upload is the same.

UPD: `securego/gosec@master` action uses docker image `v2.21.2`, though issue with SARIF output still exists. ([link](https://github.com/konflux-ci/build-service/actions/runs/10809626644/job/29985135649) to workflow run)

### Steps to reproduce the behavior

Use `securego/gosec:2.21.2` GitHub action against any repository with SARIF output upload to GitHub Advanced Security Dashboard.

### gosec version

GitHub action `securego/gosec@v2.21.2`.

### Go version (output of 'go version')

No go setup has been performed.

### Operating system / Environment

`ubuntu-latest` default GitHub runner.

### Expected behavior

GitHub action pulls `securego/gosec:2.21.2` image.

### Actual behavior

GitHub action pulls `securego/gosec:2.21.1` image with broken SARIF output.

**Comment by ccojocar** [comment]
Action was updated to 2.21.2 https://github.com/securego/gosec/blob/5f3194b581979e508b0ba1ee22f1f1f85a314e16/action.yml#L13.

Also the sarif output was successfully uploaded in Github. See the output of https://github.com/securego/gosec/actions/runs/10775152002/job/29878917216

**Comment by nickeskov** [comment]
@ccojocar Workflow uses `securego/gosec@master`, [see line 18](https://github.com/securego/gosec/actions/runs/10775152002/workflow#L18).

**Comment by alexeykiselev** [comment]
Hi @ccojocar,
I kindly ask if you could consider reopening the issue, as it seems there might be an inconsistency with tag 2.21.2 of `securego/gosec`.

> Also the sarif output was successfully uploaded in Github. See the output of https://github.com/securego/gosec/actions/runs/10775152002/job/29878917216

In your run, it appears that `securego/gosec` is using the `master` branch, see line 33 of the output https://github.com/securego/gosec/actions/runs/10775152002/job/29878917216#step:1:37.

On our side, we're using the tag `v2.21.2`, which seems to be pulling a previous version of the Docker image. Please, see line 33 from our run: https://github.com/wavesplatform/gowaves/actions/runs/10812421492/job/29994022318?pr=1492#step:1:37

I understand this issue was previously closed, but I would greatly appreciate it if you could take another look.

Thank you for your time and consideration!

**Comment by nickeskov** [comment]
> as it seems there might be an inconsistency with tag 2.21.2 of `securego/gosec`.

I've noticed that the tag [2.21.2](https://github.com/securego/gosec/releases/tag/v2.21.2) is linked to commit [abfe8cf](https://github.com/securego/gosec/commit/abfe8cfd6d5687c96abf31f8e7f57982df2a6e4f), though the action update was made in the next commit [5f3194b](https://github.com/securego/gosec/commit/5f3194b581979e508b0ba1ee22f1f1f85a314e16), which is the `HEAD` of the master branch.

**Comment by ccojocar** [comment]
> Workflow uses securego/gosec@master, [see line 18](https://github.com/securego/gosec/actions/runs/10775152002/workflow#L18).

It is the action version from the master branch, but inside of that action is using gosec version 2.21.2 as I pointed above.
