### ISSUE TITLE
G107 Incorrect behaviour

### ISSUE THREAD

**Issue by impronunciable** [securego/gosec#237]
First of all, thanks for the library, is great 🙌

### Summary 

After the gosec update that adds G107 I'm seeing an issue for every call to a "Get" function. Most of them are not "net/http" Get calls. 

### Steps to reproduce the behavior

Example:

```go
package main

import (
	"math/rand"
	"strconv"
)

type Foo struct{}

func (f Foo) Get(foo string) {
}

func main() {
	bar := Foo{}
	baz := strconv.Itoa(rand.Intn(4))
	bar.Get(baz)
}
```

### gosec version

1.1.0

### Go version (output of 'go version')

1.10.2

### Operating system / Environment

darwin/amd64

### Expected behavior

Only catch net/http url calls

### Actual behavior

Get a warning for any get call

**Comment by ccojocar** [comment]
@impronunciable Thanks for reporting this issue.

@cschoenduve-splunk Please could you have look at it, it seems to be related to your changes. Thanks

**Comment by ccojocar** [comment]
@cschoenduve-splunk I would be great if you could add this code sample to the test suite.

**Comment by cschoenduve-splunk** [comment]
@ccojocar These were the possible false positives that I was mentioning in the PR. Since we can't identify anything about the selector through using the `Type` library, it is not possible (to my knowledge) to resolve when a `Get` is really a wrapped `net/http` function call or something else. I think we would need data flow analysis to get this functionality working with low false positives.  I will remove that feature for now.

**Comment by impronunciable** [comment]
Thanks for the fast reply!
