### ISSUE TITLE
Marking False Positives in config file

### ISSUE THREAD

**Issue by schreddies** [securego/gosec#451]
### Summary 
I would like to start discussion about adding new feature of having all annotations in code for suppressing the false positives in one file, not in the code. The idea behind this is to separate application logic, from the gosec logic and make CI/CD implementation easier with GoSec.
### Steps to reproduce the behavior
Right now, to suppress the issue from gosec, the following code is required
```
import "md5" // #nosec

func main(){

    /* #nosec */
    if x > y {
        h := md5.New() // this will also be ignored
    }

}
```
Having all 'not and issue' issues marked in one file (maybe json), it would be much easier for auditing and controlling this procedure. It gives also possibility to link multiple suppressions to one part of the code. It might be helpful to automation purposes in CI/CD.
### gosec version
All
### Go version (output of 'go version')
All
### Operating system / Environment
All
### Expected behavior
Having an option to group all suppress of the code in one file.
### Actual behavior
No option, other than suppressing each part of the code

**Comment by ccojocar** [comment]
It is possible to disable a rule for an entire project by providing it as an option, like this:

```
gosec -exclude=G303
```

This idea is interesting but probably each file and the line where the warning is disabled need to be specified in the configuration. Do you think maybe to disable these rules for an entire file? 

I believe that it will be difficult to keep the config file up to date since the code gets refactored, new line added or the files gets renamed/moved. Every time something like this happens, the config needs to be updated, which is not really easy to achieve because usually people forget about these checks. 

Probably, it is better to have a similar option like pylint which allows to disable various checks by placing them somewhere at the top of the file like this:
```
# pylint: disable=C0103,C0301
```

**Comment by schreddies** [comment]
@ccojocar Thanks for answer! However, I would like to leave rules to the rest of the code and only disable only part of the code from specific rule. The idea with disabling rules per files might be closer to ideal, especially for CI/CD. The point is during refactor it might be also hard with leaving same rules properly applied. Anyway it might be flexible solution, using both or three solutions. Are the pull request welocme?

**Comment by ccojocar** [comment]
Definitely, a pull request is welcome.

**Comment by ccojocar** [comment]
@schreddies Are you still interested on this work?

**Comment by ccojocar** [comment]
Closing this since there isn't enough interest from the original reporter to work on this.
