### ISSUE TITLE
Fetching Internal Dependencies before running gosec

### ISSUE THREAD

**Issue by rafaveira3** [securego/gosec#504]
### Summary 

Hey, gosec community! Thanks for working on this awesome tool. It helps a lot of DEVs that are using [huskyCI](https://huskyci.opensource.globo.com/) in their CI pipelines. I got a question and would be very thankful if we can discuss it.

When a project does not have a `vendor` folder, gosec tries to fetch all dependencies before running, which is great. However, when these dependencies are internal ones, gosec (or Go? OS?) prompts that the system can't check the authenticity of the host and asks for the remote password.

As we are running gosec as a container, having an IO inside it is pretty bad as it will be up forever. Do you have any idea how we could tackle this one? 🙃

### Steps to reproduce the behavior

```sh
$ docker run -v ~/go/src/internalRemote/internalteam/internalproject/:/go/src/code -it huskyci/gosec:v2.3.0 sh
/go/src # cd code
/go/src/code # gosec ./...
[gosec] 2020/07/09 13:41:18 Including rules: default
[gosec] 2020/07/09 13:41:18 Excluding rules: default
[gosec] 2020/07/09 13:41:18 Import directory: /go/src/code/measures
The authenticity of host 'internalRemote (10.0.0.10)' can't be established.
ECDSA key fingerprint is SHA256:uanaXunASUnausaunANXuASuxnasu.
The authenticity of host 'internalRemote (10.0.0.10)' can't be established.
ECDSA key fingerprint is SHA256:uanaXunASUnausaunANXuASuxnasu.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
root@internalRemote's password:
```

### gosec version

v2.3.0

### Go version (output of 'go version')

go version go1.14.2 linux/amd64

### Operating system / Environment

Docker container (huskyci/gosec:v2.3.0) with [this Dockerfile](https://github.com/globocom/huskyCI/blob/master/deployments/dockerfiles/gosec/Dockerfile)

**Comment by ccojocar** [comment]
Hi there, 

I think that you need to set the `GOPRIVATE` environment variable to point to the private repository. You can find more details on https://stackoverflow.com/questions/58305567/how-to-set-goprivate-environment-variable. In addition, you will have to properly configure the private git access in order to access this module.

This is specific to Go build and not gosec. Are you able to build this project with `go build`?

**Comment by rafaveira3** [comment]
Hey, @ccojocar. The `go build` command prompts the same output as mentioned above asking for the password and the check auth error. 

We are running gosec using [these commands](https://github.com/globocom/huskyCI/blob/master/api/config.yaml#L57) inside the container and maybe we should add this `GOPRIVATE` somehow during this process. I see we may have some challenges here in huskyCI on how to scale this scenario to anyone using it.

Thanks a lot for the quick response and the guidance! 😉

**Comment by ccojocar** [comment]
> The go build command prompts the same output as mentioned above asking for the password and the check auth error.

You should fix that first in order to get the gosec scanning working because it relies on `go build` to load the modules.

`GOPRIVATE` is really specific to the project that is being scanned, but it can be easily set in the `docker run` command with `--env` option. 

Also note that our official docker image is `securego/gosec` not `huskyci/gosec`. 

That being said, we are not planning to implement any fix for this because it is outside of the scope of gosec. Anyhow thank you for reporting this issue!
