### ISSUE TITLE
HTML report 

### ISSUE THREAD

**Issue by mmorel-35** [securego/gosec#612]
Is the html report used by anyone ?
How is it maintained ?
If it's of any use, maybe it worth to create a gosec-react project in securego so it can grow ?
The build would generate a bundled html file to be used in gosec.
I can initiate the first skeleton of the project but we are going to need the support of react and node developers for the maintenance and evolution.

**Comment by ccojocar** [comment]
I would try to avoid any additional dependencies to react or nodejs. gosec is shipped as a stand-alone only and self-contained binary. I would prefer a static HTML report as of today with some javascript files fetched from a CDN.

**Comment by mmorel-35** [comment]
My suggestion is to create a https://github.com/securego/gosec-react project which would generate the actual template file used in gosec html report generation.

So on gosec point of view you'll always have a static HTML report.

Creating gosec-react would allow : 
* Maintenance of JS and CSS dependencies with NPM, just for example, the gosec dependencies and there actual version
  *  bulma 0.2.1 => 0.9.2
  * react 15.3.2 => 17.0.2
  * babel-standalone 6.17.0 => @babel/standalone 7.14.1
* New contributions by end users
* Minification of the JS and CSS content
* No need for internet access to consult the report

**Comment by ccojocar** [comment]
It makes sense but I wouldn't see this additional web app as a priority because most of the people use gosec in their CI pipeline which some textual output. The HTML report is more for audit propose when someone wants a nice report for a code audit session. 

This is also a bit out of scope for gosec project. If you are able to create and maintain a fully working web app for the report, I am happy to accept that contribution in a separate repository.

**Comment by ccojocar** [comment]
@mmorel-35 Are you still interested to pursue this issue after you improved the design? If no, I think that we can close it. Thanks!

**Comment by mmorel-35** [comment]
I agree, we can close it
