### ISSUE TITLE
G104 is no longer working as expected

### ISSUE THREAD

**Issue by squaresurf** [securego/gosec#671]
### Summary 

v2.8.1 isn't surfacing the same G104 errors as v2.8.0.

### Steps to reproduce the behavior

See https://gitlab.com/dsearles/gosec-104-example

### gosec version

v2.8.1 contains the difference.

### Go version (output of 'go version')

golang:1.15-alpine docker image

### Operating system / Environment

alpine linux

### Expected behavior

The G104 error is found on line 11.

### Actual behavior

The G104 error is not in the output.

**Comment by nanikjava** [comment]
Looks like this particular commit https://github.com/securego/gosec/pull/648 broke the previous rule that was flagged as error in `v2.8.0`

The problem is that particular commit does not have a test case too, which makes it bit hard to know which behaviour is the correct behaviour. Probably @ccojocar can provide more insight which behaviour is the correct behaviour.

Able to generate the error with the sample code provided by @squaresurf when removing this code

`whitelist.Add("hash.Hash", "Write")` 

from `errors.go`

**Comment by squaresurf** [comment]
Great find @nanikjava! As https://github.com/securego/gosec/pull/648 and https://pkg.go.dev/hash#Hash explains, `Hash.Write` will never return an error that can be unhandled.

Thank you for the help tracking that down.
