### ISSUE TITLE
Gosec integrated in Scanmycode CE (Community Edition) 

### ISSUE THREAD

**Issue by marcinguy** [securego/gosec#787]
Hi,

I would like to share information about my Open Source and selfhosted Code Scanning (Quality & Security) solution here.

We also added your Gosec for checking Go code.

Here is the repository for the Community Edition of the solution (Code & Wiki)

https://github.com/marcinguy/scanmycode-ce

For transparency, I was involved and am involved in building of it. Took several months with several people.

Thank you for Gosec being there.

Feel free to contact my directly or here in case of any questions/comments.

Thanks,

**Comment by ccojocar** [comment]
Hi @marcinguy, Thanks for this info! I am happy that gosec does its job for your code scanning solution. You can add your project to the `Used By` section if you like, https://github.com/securego/gosec/network/dependents?package_id=UGFja2FnZS0yMjY0ODE5MzI3. 

I am closing this issue since it doesn't relate to any bug or feature request.  Thanks again!
