### ISSUE TITLE
RFE: flag uses of top level net/http ListenAndServe(TLS), Serve(TLS)

### ISSUE THREAD

**Issue by scop** [securego/gosec#833]
### Summary 

- https://pkg.go.dev/net/http#ListenAndServe
- https://pkg.go.dev/net/http#ListenAndServeTLS
- https://pkg.go.dev/net/http#Serve
- https://pkg.go.dev/net/http#ServeTLS

These functions offer no possibility to set various things essential for "production" use. For example, but not limited to, timeouts cannot be set, which means they are suspect to the Slowloris class of attacks.

Some further reading:

- https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/
- https://blog.cloudflare.com/exposing-go-on-the-internet/

### Steps to reproduce the behavior

Run gosec against code that uses these functions, for example their godoc examples.

### gosec version

Current master branch.

### Expected behavior

Uses of mentioned functions get flagged.

### Actual behavior

Uses are not flagged at the moment.

**Comment by kaihendry** [comment]
I think the upstream Go issue is https://github.com/golang/go/issues/54136 and should be fixed in 1.20 🤞

Tbh I feel the security checker `gosec`should check security issues in the code I write [(eg)](https://github.com/securego/gosec/issues/569), **not flag an issue in an upstream API** which is typically unexploitable considering Go programs are typically deployed behind a protective reverse proxy.

**Comment by scop** [comment]
> unexploitable considering Go programs are typically deployed behind a protective reverse proxy.

I feel this is a dangerous generalisation.

**Comment by kaihendry** [comment]
@scop Can you explain why please?

Can I assume you are talking in the context of a Slowloris DDOS?

**Comment by charego** [comment]
As @kaihendry said, the upstream issue is fixed in Go 1.20.

Is it possible to only emit a warning on earlier Go versions?
