### ISSUE TITLE
Need a new project / org name

### ISSUE THREAD

**Issue by gcmurphy** [securego/gosec#85]
This project has been about for longer than ours: https://github.com/go-gas/gas so I guess we should look at coming up with a different name. 

@GoASTScanner/committers  Any suggestions for new project name / org name?

**Comment by endophage** [comment]
Something that emphasizes the security aspect rather than the AST aspect would be great 👍

**Comment by alaska** [comment]
Cogminder
Rearguard - Connotes vigilence / pun for CYA
Argus - Greek mythology, a many-eyed giant. Guardian, sees all.
Daimon - Sort of personal spirit guardians/tutors from Greek mythology.
Securitas - yeah, turns out there's a god for that.
Stata Mater - Another Roman pantheon goddess. She protected against fires. And, hey, what do security bugs cause? :D
Coeus - titan of rational knowledge
Aegis - shield/protective artifact

**Comment by cosmincojocar** [comment]
What about **gosec**, it sounds more appropriate for this tool.

**Comment by thiderman** [comment]
The target project is comptely empty now though? Maybe a name change is not needed?

**Comment by gcmurphy** [comment]
Finally got around to doing this!
