### ISSUE TITLE
No issues reported for secDevLabs (vulnerable apps)

### ISSUE THREAD

**Issue by aleisalem** [securego/gosec#885]
### Summary 
I am new to using gosec. So, I was trying it against a set of vulnerable go apps in the [secDevLabs](https://github.com/globocom/secDevLabs). The tools reports absolutely no issues although the apps are designed to be vulnerable with some of the vulnerabilities being really obvious (e.g., concatenated SQL statements for SQLi). Am I doing something wrong? Thanks a lot in advance :)

### Steps to reproduce the behavior

1. Clone, for example, the [copy-n-paste](https://github.com/globocom/secDevLabs/blob/master/owasp-top10-2021-apps/a3/copy-n-paste/) app which is vulnerable to SQL injection attacks.
2. Go to the `app/` directory (not sure if necessary but it avoids "failed to import" errors).
3. Run `gosec ./... --verbose` (just to check the vulnerable files are scanned).

### gosec version
v2.14.0

### Go version (output of 'go version')
go1.18.7 linux/amd64

### Operating system / Environment
Ubuntu Linux 22.04

### Expected behavior
I expect to see some security issues like in line [49](https://github.com/globocom/secDevLabs/blob/904a2fb969cb9fb0db30b50709072da8f9d57002/owasp-top10-2021-apps/a3/copy-n-paste/app/util/db.go#L49) according to the rule **G202: SQL query construction using string concatenation**. 

### Actual behavior
The tools reports zero issues:
Summary:
  Gosec  : v2.14.0
  Files  : 6
  Lines  : 391
  Nosec  : 0
  Issues : 0

**Comment by ccojocar** [comment]
I think on a first look that we should detect this issue, but it seems that somehow the SQL rule doesn't. This looks like a bug to me.

**Comment by audunmo** [comment]
Might be that some of these apps from secDevLabs could be good to benchmark the performance of gosec?

**Comment by audunmo** [comment]
I have a hypothesis of why this is happening, will try to implement a fix

**Comment by audunmo** [comment]
So I've been looking a bit at why `gosec` doesn't flag the SQL injections in secDevLabs. The hypothesis I've been working from is that the failure arises because of how `gosec` handles SQLi via format calls seperately from how it handles SQLi via string concatenations. I still haven't properly confirmed this hypothesis, nor have I found a good fix to the problem.

However, I've been doing some digging. I've added a test case for the case of combined formatting and concatenation, and gosec does _not_ catch it. What I've observed is that when handling this case, the formatting checker only gets the last string in the concatenation. So `fmt.Sprintf("SELECT * FROM x WHERE '" + os.Args[1] + "' = 'lala'")` only produces `"' = 'lala'"` for inspection by `gosec`. You can see this behaviour in my fork, running `dlv test --build-flags='github.com/securego/gosec/v2/rules'` and inspecting the locals. Screenshot attatched: <img width="975" alt="Screenshot 2023-07-14 at 14 18 31" src="https://github.com/securego/gosec/assets/5461437/61ace49d-89ec-4c96-801d-3f692c51126d">

**Comment by audunmo** [comment]
Just saw that the SQL is borked.. Disregard that 😅

**Comment by ccojocar** [comment]
SQL injections rule needs a revamp to catch more advanced issue. Closing this for now.
