### ISSUE TITLE
G307 - defer http.Body.Close() is not wrong

### ISSUE THREAD

**Issue by szuecs** [securego/gosec#925]
### Summary 

https://github.com/securego/gosec/issues/890 requested that not everything that does `defer http.Body.Close()`

I think there is a clear miss understanding here.
Close() is not a problem on http.Body, because in case you got a response you have an in-memory data structure that you can close without a serious possibility of a fail. 
A filesystem with a device and device driver and layers of vfs is a completely different thing. 
Right now I don't see a reasoning about the change done in https://github.com/securego/gosec/pull/897. I think this should be reverted if there is no clear idea why this makes sense.

**Comment by mwolfe-arkose** [comment]
Seconded. I just ran into this issue and I don't believe it's appropriate for G307 to trigger on an `io.ReadCloser` like we have with HTTP request bodies (in a server) or response bodies (in a client)

 My understanding of the G307 check is that it's supposed to guard against cases where _writes aren't committed_ until `Close` is called and therefore an error return from `Close` could imply data loss. Since an `io.ReadCloser` can't be written to, there is no such risk - my understanding of the interface is that `io.ReadCloser`'s `Close` is more of an advisory call. While it might be appropriate in some cases to log errors that occur when closing an `io.ReadCloser`, they should only represent "failure to release the underlying data structure" (such as a HTTP connection, which I assume is where this is mostly going to come up) rather than "failure to commit in-flight write operations".

In this particular case, attempting to close a HTTP request (on the server) or response (on the client) will fail if the HTTP subsystem can't read any remaining body and trailer information to prepare the connection for reuse. The practical effect of this will be that the HTTP connection won't be reused, causing _at worst_ a minor performance impact, and most clients and servers won't have anything meaningful to do in response to that error.

**Comment by TimonOmsk** [comment]
Hello guys! 

First of all, the main idea of SAST tools is "False-positive is better than missing an issue". 
Missing an issue can cost you much more than just set "ignore" annotation to particular line(if you're a 100% sure it's a true false-positive).
Next. Please take a look on the following issue - https://github.com/golang/go/issues/49366. Here you can find an example where you can get an error from body.Close() function. SAST software can't rely on the internal details of implementation, if something possible by agreement(interface in that particular case) we should take it into account no matter of our knowledge of internal implementation in the 3rd-party(and golang itselft is a 3rd party here) software.

**Comment by ccojocar** [comment]
@szuecs @mwolfe-arkose Thanks for clarifications but I think the check is still relevant is some cases as @TimonOmsk commented above. 

You can exclude the check in your scan using the `-exclude` command option if you want.

**Comment by szuecs** [comment]
@ccojocar ok then I will better not use the tool. Thanks for clarifying that you want to be a linter with wrong false positives rather than some serious usable tool.

**Comment by mwolfe-arkose** [comment]
I wouldn't say `G307` triggering on `io.ReadCloser`s is a _false_ positive - it's technically correct, the `Close` call _can_ return an error - just that flagging it by default is incredibly pedantic compared to `os.File` or `io.WriteCloser`. In fact, your referenced Go issue says at the bottom:

> I realize it's weird to be checking the `resp.Body.Close` error in the first place. This came up in the context of [twirp](https://github.com/twitchtv/twirp); I'm going to send a PR to them to stop checking the error.

Again, I just think it's a different class of issue than deferring `Close` on a writeable object. Deferring `Close` on an `os.File` is "you might lose data", deferring `Close` on a `http.Request.Body` is "you might maybe not log an error message".

Also, while I agree in principle that it's better to trigger more lints and let users `//#nosec` or disable the ones they don't need, that's not always practical in a large team / enterprise environment. "Everyone comes in on Monday and now all our CI pipelines are failing with new lint errors that aren't obvious about what changed" is pretty much a nightmare scenario for anyone in the devops business. I think I'd rather have seen this change implemented as a new rule or a gradual roll-out "hey this is going to become an error in future" warning that doesn't force me (and all my teammates) to make a call about whether I should add forty lines of `//#nosec`s to an unrelated PR, disable the `G307` rule entirely, or roll back to an older `gosec` version (now that that's possible via #927, thanks for that!)

**Comment by AlexanderYastrebov** [comment]
I think `defer rsp.Body.Close()` is very common and the tool should probably treat it differently from other `io.ReadCloser`s.
I've also created https://github.com/golang/go/issues/58406 to clarify that.

**Comment by ccojocar** [comment]
Thank you for the comments. I am happy to accept an improvement form you. Please feel free to raise a pull request.

**Comment by hiohiohio** [comment]
G307 was retired by https://github.com/securego/gosec/pull/935
